---
- name: "adding nodejs"
  become: true
  shell: |
    curl -fsSL https://deb.nodesource.com/setup_19.x | sudo -E bash - &&\

- name: "installing nodejs"
  become: true
  apt:
    name: ["nodejs"]
    state: latest
    update_cache: yes

- name: "installing pm2"
  become: true
  apt:
    name: pm2
    global: yes