---
- name: create backend folder
  file: 
    path: ~/backend_application
    state: directory

- name: "un tar"
  unarchive:
    src: artifact.tar.gz
    dest: ~/backend_application

- name: "installing dependencies"
  shell: |
    cd ~/backend_application
    npm i

- name: "executing"
  shell: |
    cd ~backend/dist
    npm install
    pm2 stop default
    pm2 start npm -- start