---
- name: create backend folder
  file: 
    path: ~/backend_application
    state: directory

- name: "getting path"
  shell: |
    pwd
    ls -la

- name: "un tar"
  unarchive:
    src: /home/circleci/project/.circleci/ansible/roles/deploy/files
    dest: ~/backend_application

- name: "installing dependencies"
  shell: |
    cd ~/backend_application
    npm install

- name: "executing"
  shell: |
    cd ~/backend_application/dist
    pm2 stop default
    pm2 start main.js