---
- name: create backend folder
  file: 
    path: ~/backend_application
    state: directory

- name: "un tar"
  unarchive:
    src: backend/artifact.tar.gz
    dest: ~/backend_application

- name: "installing dependencies"
  shell: |
    cd ~/backend_application
    npm install

- name: "executing"
  shell: |
    cd ~/backend_application/dist
    pm2 stop default
    pm2 start main.js