---
- name: create backend folder
  files: 
    path: ~/backend
    state: directory

- name: "un tar"
  unarchive:
    src: artifact.tar.gz
    dest: ~/backend

- name: "installing dependencies"
  shell: |
    cd ~/backend
    npm i

- name: "executing"
  shell: |
    cd ~backend/dist
    npm install
    pm2 stop default
    pm2 start npm -- start